# ==== BUILDER ====
FROM mcr.microsoft.com/powershell:lts-7.2-ubuntu-22.04 AS builder
run 
WORKDIR /tmp/drawthenet.io

RUN apt update && apt -y install git wget build-essential cmake libemf2svg-dev librevenge-dev libwmf-dev libvisio-dev

RUN git clone https://github.com/kakwa/libvisio2svg.git -b master
WORKDIR /tmp/drawthenet.io/libvisio2svg
RUN cmake . -DCMAKE_INSTALL_PREFIX=/usr/ && make && make install

# Build drawthenet.io
WORKDIR /tmp/drawthenet.io/
RUN git clone https://github.com/remygrandin/drawthenet.io.git -b master
WORKDIR /tmp/drawthenet.io/drawthenet.io/tools
run pwsh ./build.ps1



