# ==== BUILDER ====
FROM mcr.microsoft.com/powershell:7.3-ubuntu-22.04 AS builder
WORKDIR /tmp/drawthenet.io

RUN apt update && apt -y install git wget build-essential cmake libemf2svg-dev librevenge-dev libwmf-dev libvisio-dev

RUN git clone https://github.com/kakwa/libvisio2svg.git -b master
WORKDIR /tmp/drawthenet.io/libvisio2svg
RUN cmake . -DCMAKE_INSTALL_PREFIX=/usr/ && make && make install

# Build drawthenet.io
WORKDIR /tmp/drawthenet.io/
RUN git clone https://github.com/remygrandin/drawthenet.io.git -b master
WORKDIR /tmp/drawthenet.io/drawthenet.io/tools
run pwsh ./build.ps1


# ==== RUNNER ====
FROM ubuntu:latest

## Application Port
EXPOSE 80

# Installing Nginx
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt -y install nginx ca-certificates

COPY --from=builder /tmp/drawthenet.io/drawthenet.io/dist /opt/drawthenet.io

RUN rm /etc/nginx/sites-available/default && rm /etc/nginx/sites-enabled/default
COPY drawthenet.io.nginx.conf /etc/nginx/sites-available/drawthenet.io.nginx.conf
RUN ln -s /etc/nginx/sites-available/drawthenet.io.nginx.conf /etc/nginx/sites-enabled/drawthenet.io.nginx.conf

# Run the specified command within the container.
CMD ["nginx", "-g", "daemon off;"]

